project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: briefcase
        text: CV
        href: media/dsk_resume.pdf


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    include-in-header: 
      text: | 
        <meta name="robots" content="noindex,nofollow"/>




