project:
  type: website
  output-dir: docs

website:
  favicon: media/CleanShot 2026-03-23 at 17.28.16@2x.png
  navbar:
    search: false # search bar disabled
    left:
      - href: index.qmd
        text: Home
      - href: writings.qmd
        text: Writings
      - text: CV
        href: media/dsk_resume.pdf
  page-footer:
    right: This website is inspired by [Samantha Csik's](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank} and was built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}.

format:
  html:
    theme: styles.scss
    mainfont: Lato
    page-layout: full
    include-in-header: 
      text: | 
        <meta name="robots" content="noindex,nofollow"/>




